# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd241a8b309dfd2eea131035dd2fb7002c13701933e1c7e1b47c67db86bf7a651515e9f39c50fca644a4c37b9fe4e82c97d456b4db8b300fb8cc62b0684b604b

test:
  secret_key_base: 13c8144f09dd7724588c8eb061aaf3b2ee244f213b98638c3e542166aabc25b3a220ab5403f62b16b28f0ae34984b4668ea464b44bf75b9a3e0b74e53d701f2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
